services:
  - type: cron
    name: weather-pipeline
    runtime: docker
    repo: https://github.com/MpiloG29/Weather-Data-Pipeline-Project-
    branch: master
    dockerfilePath: ./Dockerfile
    schedule: "0 * * * *"  # Runs every hour
    envVars:
      - key: DATABASE_URL
        value: sqlite:///data/weather_data.db